parameters:
    env(DATABASE_URL): ''
    database_driver: pdo_sqlsrv
    #database_host: 192.168.88.62
    database_host: 154.126.56.88
    database_port: 1433
    database_name: ComptaTrav
    database_user: sa
    database_password: 123Paoma456
doctrine:
    dbal:
        #by ftr
        driver:   '%database_driver%'
        host:     '%database_host%'
        dbname:   '%database_name%'
        user:     '%database_user%'
        password: '%database_password%'
        port: '%database_port%'
        #end ftr

        #url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
